version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - ${PROJECT_DIR}/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_USER} -U ${POSTGRES_PASSWORD}" ]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES}
    ports:
      - "5432:5432"
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    environment:
      DB: postgresql
      DB_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      POSTGRES_SEEDS: ${POSTGRES_HOST}
    ports:
      - "7233:7233"
    depends_on:
      - postgres
  temporal_admin_tools:
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_HOST}:${TEMPORAL_PORT}
      TEMPORAL_CLI_ADDRESS: ${TEMPORAL_HOST}:${TEMPORAL_PORT}
    stdin_open: true
    tty: true
    depends_on:
      - temporal
  temporal_ui:
    environment:
      TEMPORAL_ADDRESS: ${TEMPORAL_HOST}:${TEMPORAL_PORT}
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - temporal
