modules:
  - config
  - queue

queue:
  url:
  repeats:
    - 30s
    - 1m
    - 5m
    - 15m
    - 30m
    - 1h
    - 2h
    - 4h
    - 8h
    - 12h
    - 1d

pipes:
  - name: email
    replicas: 10
    stages:
      - type: receive
        components:
          - queue/receiver
      - type: middleware
        component: component1
      - type: parallel_middleware
        components:
          - component2
          - component3
          - component4
      - type: complete
        component: email/sender