pipelines:
  - name: email
    replicas: 10
    stages:
      - type: receive
        components:
          - name: rabbitmq/receiver
            config:
              prefix: postmanq
              url:
              repeats:
                - 30s
                - 1m
                - 5m
                - 15m
                - 30m
                - 1h
                - 2h
                - 4h
                - 8h
                - 12h
                - 1d
      - type: parallel_middleware
        components:
          - name: smtp/parser
      - type: parallel_middleware
        components:
          - name: smtp/signature
      - type: complete
        component:
          name: smtp/sender
          config:
            hostname: mail.postmanq.io
            ips:
              - 1.1.1.1
              - 2.2.2.2
              - 3.3.3.3