pipelines:
- name: marketing_mailing
  plugins:
  - name: rabbitmq
    config:
      url:
      queue: postmanq
      repeats:
        - 30s
        - 1m
        - 5m
        - 15m
  - name: smtp
    config:
      hostname: mail.postmanq.io
      ips:
        - 1.1.1.1
        - 2.2.2.2
        - 3.3.3.3