// Code generated by mockery v1.0.0. DO NOT EDIT.

package factory

import (
	entity "github.com/postmanq/postmanq/module/pipe/entity"

	mock "github.com/stretchr/testify/mock"

	service "github.com/postmanq/postmanq/module/pipe/service"
)

// PipelineFactory is an autogenerated mock type for the PipelineFactory type
type PipelineFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *PipelineFactory) Create(_a0 entity.Pipeline) (service.Pipeline, error) {
	ret := _m.Called(_a0)

	var r0 service.Pipeline
	if rf, ok := ret.Get(0).(func(entity.Pipeline) service.Pipeline); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.Pipeline)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entity.Pipeline) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
