// Code generated by MockGen. DO NOT EDIT.
// Source: postmanq/services.go
//
// Generated by this command:
//
//	mockgen -source postmanq/services.go -destination postmanq_mocks/services.go
//
// Package mock_postmanq is a generated GoMock package.
package mock_postmanq

import (
	context "context"
	reflect "reflect"

	rxgo "github.com/reactivex/rxgo/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// OnReceive mocks base method.
func (m *MockPlugin) OnReceive(ctx context.Context, next chan<- rxgo.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnReceive", ctx, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnReceive indicates an expected call of OnReceive.
func (mr *MockPluginMockRecorder) OnReceive(ctx, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnReceive", reflect.TypeOf((*MockPlugin)(nil).OnReceive), ctx, next)
}

// OnSend mocks base method.
func (m *MockPlugin) OnSend(ctx context.Context, item rxgo.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnSend", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnSend indicates an expected call of OnSend.
func (mr *MockPluginMockRecorder) OnSend(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSend", reflect.TypeOf((*MockPlugin)(nil).OnSend), ctx, item)
}
