// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import (
	module "github.com/postmanq/postmanq/module"
	mock "github.com/stretchr/testify/mock"
)

// ConfigProviderFactory is an autogenerated mock type for the ConfigProviderFactory type
type ConfigProviderFactory struct {
	mock.Mock
}

// CreateFromMap provides a mock function with given fields: _a0
func (_m *ConfigProviderFactory) CreateFromMap(_a0 map[string]string) (module.ConfigProvider, error) {
	ret := _m.Called(_a0)

	var r0 module.ConfigProvider
	if rf, ok := ret.Get(0).(func(map[string]string) module.ConfigProvider); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(module.ConfigProvider)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
