swagger: "2.0"
info:
  title: postmanq/v1/postmanq.proto
  version: version not set
tags:
  - name: EventService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/event:
    post:
      operationId: EventService_ReceiveEvent
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/Event'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Status'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Event'
      tags:
        - EventService
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Event:
    type: object
    properties:
      uuid:
        type: string
      attempts_count:
        type: integer
        format: int64
      from:
        type: string
      to:
        type: string
      data:
        type: string
        format: byte
      template:
        type: string
      vars:
        type: object
        additionalProperties:
          type: string
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/Any'
