swagger: "2.0"
info:
  title: api/proto/postmanq/v1/enum.proto
  version: version not set
tags:
  - name: EventService
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/event:
    post:
      operationId: EventService_ReceiveEvent
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/Event'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/Status'
      parameters:
        - name: uuid
          in: query
          required: false
          type: string
        - name: attempts_count
          in: query
          required: false
          type: integer
          format: int64
        - name: from
          in: query
          required: false
          type: string
        - name: to
          in: query
          required: false
          type: string
        - name: data
          in: query
          required: false
          type: string
          format: byte
        - name: template
          in: query
          required: false
          type: string
        - name: vars[string]
          description: This is a request variable of the map type. The query format is "map_name[key]=value", e.g. If the map name is Age, the key type is string, and the value type is integer, the query parameter is expressed as Age["bob"]=18
          in: query
          required: false
          type: string
      tags:
        - EventService
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Event:
    type: object
    properties:
      uuid:
        type: string
      attempts_count:
        type: integer
        format: int64
      from:
        type: string
      to:
        type: string
      data:
        type: string
        format: byte
      template:
        type: string
      vars[string]:
        type: object
        additionalProperties:
          type: string
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/Any'
