swagger: "2.0"
info:
  title: server/v1/services.proto
  version: version not set
tags:
  - name: EventService
consumes:
  - application/json
produces:
  - application/json
paths: {}
definitions:
  Any:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  Event:
    type: object
    properties:
      uuid:
        type: string
      attempts_count:
        type: integer
        format: int64
      from:
        type: string
      to:
        type: string
      data:
        type: string
        format: byte
      template:
        type: string
      vars:
        type: object
        additionalProperties:
          type: string
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/Any'
