// Code generated by mockery v1.0.0. DO NOT EDIT.

package stage

import (
	module "github.com/postmanq/postmanq/module"
	mock "github.com/stretchr/testify/mock"

	stage "github.com/postmanq/postmanq/module/pipe/service/stage"
)

// DeliveryStage is an autogenerated mock type for the DeliveryStage type
type DeliveryStage struct {
	mock.Mock
}

// Bind provides a mock function with given fields: _a0
func (_m *DeliveryStage) Bind(_a0 stage.Stage) {
	_m.Called(_a0)
}

// Deliveries provides a mock function with given fields:
func (_m *DeliveryStage) Deliveries() chan module.Delivery {
	ret := _m.Called()

	var r0 chan module.Delivery
	if rf, ok := ret.Get(0).(func() chan module.Delivery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan module.Delivery)
		}
	}

	return r0
}

// Start provides a mock function with given fields:
func (_m *DeliveryStage) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
