// Code generated by mockery v1.0.0. DO NOT EDIT.

package stage

import (
	stage "github.com/postmanq/postmanq/module/pipe/service/stage"
	mock "github.com/stretchr/testify/mock"
)

// Stage is an autogenerated mock type for the Stage type
type Stage struct {
	mock.Mock
}

// Bind provides a mock function with given fields: _a0
func (_m *Stage) Bind(_a0 stage.Stage) {
	_m.Called(_a0)
}

// Run provides a mock function with given fields:
func (_m *Stage) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
