// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// ConfigProvider is an autogenerated mock type for the ConfigProvider type
type ConfigProvider struct {
	mock.Mock
}

// Populate provides a mock function with given fields: _a0, _a1
func (_m *ConfigProvider) Populate(_a0 string, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
