// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import (
	module "github.com/postmanq/postmanq/module"
	mock "github.com/stretchr/testify/mock"
)

// Stage is an autogenerated mock type for the Stage type
type Stage struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *Stage) Init() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with given fields: _a0
func (_m *Stage) Start(_a0 <-chan module.Delivery) <-chan module.Delivery {
	ret := _m.Called(_a0)

	var r0 <-chan module.Delivery
	if rf, ok := ret.Get(0).(func(<-chan module.Delivery) <-chan module.Delivery); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan module.Delivery)
		}
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Stage) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
