on: [ push ]
jobs:
  #  test:
  #    name: Test PostmanQ
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout repo
  #        uses: actions/checkout@v4
  #      - name: Setup go
  #        uses: actions/setup-go@v4
  #      - name: Test PostmanQ
  #        run: make test
  build:
    name: Build PostmanQ
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    environment: ${{ matrix.os}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
      - name: Build PostmanQ
        run: make build
      - name: Upload linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: postmanq-${{ matrix.os }}
          path: |
            dist/*
            dist/plugins/*
  

#  build-linux:
#    name: Build PostmanQ on linux
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#      - name: Setup go
#        uses: actions/setup-go@v4
#      - name: Build PostmanQ
#        env:
#          GOOS: linux
#          GOARCH: amd64
#        run: make build
#      - name: Upload linux binaries
#        uses: actions/upload-artifact@v4
#        with:
#          name: postmanq-linux
#          path: |
#            dist/*
#            dist/plugins/*
#  build-darwin:
#    name: Build PostmanQ on darwin
#    runs-on: macos-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#      - name: Setup go
#        uses: actions/setup-go@v4
#      - name: Build PostmanQ
#        env:
#          GOOS: darwin
#          GOARCH: arm64
#        run: make build
#      - name: Upload darwin binaries
#        uses: actions/upload-artifact@v4
#        with:
#          name: postmanq-darwin
#          path: |
#            dist/*
#            dist/plugins/*
  release:
    name: Release PostmanQ
    runs-on: ubuntu-latest
    needs:
      - build
#      - build-linux
#      - build-darwin

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          pattern: postmanq-*
          merge-multiple: true
          path: dist
      - name: Release PostmanQ
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 0.0.1
          files: |
            dist/*
            dist/plugins/*
