on: [push]
jobs:
  release-postmanq:
    name: Release PostmanQ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
#        goos: [linux, windows, darwin]
#        goarch: ["386", amd64, arm64]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
    - name: Build PostmanQ
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make build_postmanq
    - name: Build PostmanQ plugins
      run: make build_plugins
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
