on: [push]
jobs:
  release-postmanq:
    name: Release PostmanQ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, freebsd]
        goarch: ["386", amd64, arm, arm64]
        exclude:
        - goos: freebsd
          goarch: arm64
        - goos: darwin
          goarch: 386
        - goos: darwin
          goarch: arm
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
    - name: Build PostmanQ
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: make build
    - name: Release postmanq
      uses: softprops/action-gh-release@v2
      with:
        tag_name: 0.0.1
        files: dist/*
