on: [push]
jobs:
  release-postmanq:
    name: Release PostmanQ
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386"]
#        goos: [linux, windows, darwin]
#        goarch: ["386", amd64, arm64]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Create .env
      run: |
        cp -f .env.dist .env
    - name: Build PostmanQ
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: "make"
        build_flags: "build_postmanq"
        binary_name: "postmanq"
